name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Python syntax
        run: |
          python -m py_compile producer/producer.py
          python -m py_compile metrics-api/main.py
          python -m py_compile spark/streaming.py

      - name: Build Docker images
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for services
        run: sleep 15

      - name: Check Metrics API
        run: curl --fail http://localhost:8000/health

      - name: Show containers
        run: docker compose ps

      - name: Stop services
        if: always()
        run: docker compose down